### ISSUE TITLE
 AuroraIMUIController.updateMessage(message) 报错

### ISSUE THREAD

**Issue by JohnTree** [jpush/jmessage-react-plugin#124]
JMessage.retractMessage(msg, (success) => {
            AuroraIMUIController.updateMessage(message)
        }, (error) => {
            console.warn(JSON.stringify(error))
 });

`E/unknown:React: Exception in native call
                                                         java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.facebook.react.bridge.ReadableMap.getString(java.lang.String)' on a null object reference
                                                             at cn.jiguang.imui.messagelist.AuroraIMUIModule.configMessage(AuroraIMUIModule.java:139)
                                                             at cn.jiguang.imui.messagelist.AuroraIMUIModule.insertMessagesToTop(AuroraIMUIModule.java:126)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
                                                             at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
                                                             at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                             at android.os.Looper.loop(Looper.java:179)
                                                             at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
                                                             at java.lang.Thread.run(Thread.java:818)`

**Comment by JohnTree** [comment]
我打印了 message 是和官方文档一样的格式

**Comment by JoshLipan** [comment]
[社区](https://community.jiguang.cn/t/topic/30941/17)讨论
