### ISSUE TITLE
debug环境下是好的，打完release包之后，报 java.lang.AssertionError

### ISSUE THREAD

**Issue by Tiger-man** [jpush/jmessage-react-plugin#149]
java.lang.AssertionError
        at cn.a.a.a.a.b.a.m$a.<init>(Unknown Source:86)
        at cn.a.a.a.a.b.a.m$19.a(Unknown Source:29)
        at cn.a.a.a.a.f.a(Unknown Source:68)
        at cn.a.a.a.a.b.a.i.a(Unknown Source:19)
        at cn.a.a.a.a.b.a.i.a(Unknown Source:0)
        at cn.a.a.a.a.b.a.i$1.<init>(Unknown Source:21)
        at cn.a.a.a.a.b.a.i.a(Unknown Source:19)
        at cn.a.a.a.a.b.a.i.a(Unknown Source:118)
        at cn.a.a.a.a.b.a.i.a(Unknown Source:22)
        at cn.a.a.a.a.f.a(Unknown Source:68)
        at cn.a.a.a.a.b.a.b.a(Unknown Source:26)
        at cn.a.a.a.a.f.a(Unknown Source:68)
        at cn.a.a.a.a.b.a.i.a(Unknown Source:19)
        at cn.a.a.a.a.b.a.i.a(Unknown Source:0)
        at cn.a.a.a.a.b.a.i$1.<init>(Unknown Source:21)
        at cn.a.a.a.a.b.a.i.a(Unknown Source:19)
        at cn.a.a.a.a.b.a.i.a(Unknown Source:118)
        at cn.a.a.a.a.b.a.i.a(Unknown Source:22)
        at cn.a.a.a.a.f.a(Unknown Source:68)
        at cn.a.a.a.a.f.a(Unknown Source:16)
        at cn.a.a.a.a.f.a(Unknown Source:5)
        at cn.a.a.a.a.f.a(Unknown Source:9)
        at cn.jpush.im.android.g.i.a(Unknown Source:6)
        at cn.jpush.im.android.i.r.a(Unknown Source:30)
        at cn.jpush.im.android.i.a.a(Unknown Source:61)
        at cn.jpush.im.android.i.a$1.a(Unknown Source:82)
        at cn.jpush.im.android.i.a$1.call(Unknown Source:0)
        at cn.jpush.im.android.a.e$2.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by JoshLipan** [comment]
加上[混淆](https://docs.jiguang.cn/jmessage/client/jmessage_android_guide/#jmessage_1)试下

**Comment by Tiger-man** [comment]
行，我试一下

**Comment by Tiger-man** [comment]
@JoshLipan 好了 万分感谢
